# Generated by Django 4.0.5 on 2022-06-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Created_date',
            field=models.DateTimeField(default=-20),
        ),
        migrations.AddField(
            model_name='post',
            name='Published_date',
            field=models.DateTimeField(default=-22),
        ),
        migrations.AddField(
            model_name='post',
            name='Text',
            field=models.TextField(default='Enter text here'),
        ),
    ]
